/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.edunova.zavrsni.view;

import hr.edunova.zavrsni.controller.ObradaKorisnik;
import hr.edunova.zavrsni.controller.ObradaOperater;
import hr.edunova.zavrsni.controller.ObradaRacun;
import hr.edunova.zavrsni.model.Racun;
import hr.edunova.zavrsni.model.Operater;
import hr.edunova.zavrsni.model.Korisnik;
import hr.edunova.zavrsni.util.Aplikacija;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
/**
 *
 * @author jalep
 */
public class ProzorRacun extends javax.swing.JFrame implements ProzorSucelje{

    private ObradaRacun obrada;
    
    /**
     * Creates new form ProzorRacun
     */
    public ProzorRacun() {
        initComponents();
        obrada = new ObradaRacun();
        postavke();
        ucitaj();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstEntiteti = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        txtBrojRacuna = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbOperater = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cmbKorisnik = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lstEntiteti.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstEntitetiValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstEntiteti);

        jLabel1.setText("Broj Racuna");

        jLabel2.setText("Operater");

        jLabel3.setText("Korisnik");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(txtBrojRacuna)
                        .addComponent(jLabel2)
                        .addComponent(cmbOperater, 0, 101, Short.MAX_VALUE))
                    .addComponent(jLabel3)
                    .addComponent(cmbKorisnik, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(253, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBrojRacuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbOperater, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbKorisnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lstEntitetiValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstEntitetiValueChanged
        if(evt.getValueIsAdjusting() || lstEntiteti.getSelectedValue()== null){
            return;
        }
        
        obrada.setEntitet(lstEntiteti.getSelectedValue());
        var r = obrada.getEntitet();
        
        txtBrojRacuna.setText(r.getBrojRacuna());
        // postaviti operatera u cmb
        // u modelu klasa operater generirao sam equals i hashCode metode - ne bih koristio
        cmbOperater.setSelectedItem(r.getOperater());
         System.out.println(r.getOperater().hashCode());
         
    }//GEN-LAST:event_lstEntitetiValueChanged

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Korisnik> cmbKorisnik;
    private javax.swing.JComboBox<Operater> cmbOperater;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Racun> lstEntiteti;
    private javax.swing.JTextField txtBrojRacuna;
    // End of variables declaration//GEN-END:variables

    @Override
    public void postaviVrijednostiUEntitet() {
        
    }

    @Override
    public void postavke() {
        setTitle(Aplikacija.getNaslov("Racuni"));
        
        
        DefaultComboBoxModel<Operater> mo = new DefaultComboBoxModel<>();
        Operater op = new Operater();
        op.setId(Long.valueOf(0));
        op.setNaziv("Nije odabrano");
        mo.addElement(op);
        new ObradaOperater().read().forEach(o->{
            System.out.println(o.hashCode());
            mo.addElement(o);});
        cmbOperater.setModel(mo);
        
        DefaultComboBoxModel<Korisnik> mk = new DefaultComboBoxModel<>();
        Korisnik k = new Korisnik();
        k.setId(Long.valueOf(0));
        k.setIme("Nije");
        k.setPrezime("odabrano");
        mk.addElement(k);
        new ObradaKorisnik().read().forEach(ko->{mk.addElement(ko);});
        cmbKorisnik.setModel(mk);
        
        
    }

    @Override
    public void ucitaj() {
        DefaultListModel<Racun> mr = new DefaultListModel<>();
        obrada.read().forEach(r->{mr.addElement(r);});
        lstEntiteti.setModel(mr);
    }
}
