/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.edunova.zavrsni.view;

import hr.edunova.zavrsni.controller.ObradaOperater;
import hr.edunova.zavrsni.util.Aplikacija;
import hr.edunova.zavrsni.model.Operater;
import javax.swing.DefaultListModel;

/**
 *
 * @author jalep
 */
public class ProzorOperater extends javax.swing.JFrame {

    private ObradaOperater obradaOperater;
    
    /**
     * Creates new form ProzorOperater
     */
    public ProzorOperater() {
        initComponents();
        obradaOperater = new ObradaOperater();
        postavke();
        ucitajOperatere();
    }

    private void postavke(){
        setTitle(Aplikacija.getNaslov("Izbornik"));
    }
    
    private void ucitajOperatere(){
        DefaultListModel<Operater> m = new DefaultListModel<>();
        
        obradaOperater.read().forEach(o->{m.addElement(o);});
        
        lstOperateri.setModel(m);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstOperateri = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(lstOperateri);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(296, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Operater> lstOperateri;
    // End of variables declaration//GEN-END:variables
}
